### Read all
GET 127.0.0.1:8080/api/teams

### Create
POST 127.0.0.1:8080/api/teams
Content-Type: application/json

{
  "name": "WhatTheFuck",
  "players": ["player_1", "player_11", "player_21", "player_31"]
}

### Read
GET 127.0.0.1:8080/api/teams/team_51e9f49a-8640-4281-8584-1f3d76ad4084

### Update
PUT 127.0.0.1:8080/api/teams/team_51e9f49a-8640-4281-8584-1f3d76ad4084
Content-Type: application/json

{
  "name": "WhatTheFuck2",
  "players": ["player_2", "player_12", "player_22", "player_32"]
}

### Delete
DELETE 127.0.0.1:8080/api/teams/team_51e9f49a-8640-4281-8584-1f3d76ad4084

### Error : Create with unknown player
POST 127.0.0.1:8080/api/teams
Content-Type: application/json

{
  "name": "WhatTheFuck2",
  "players": ["player_2", "player_0", "player_22", "player_32"]
}

### Error : Read with unknown team
GET 127.0.0.1:8080/api/teams/unknown

### Error : Update with unknown team
PUT 127.0.0.1:8080/api/teams/unknown
Content-Type: application/json

{
  "name": "WhatTheFuck2",
  "players": ["player_2", "player_12", "player_22", "player_32"]
}

### Error : Update with unknown player
PUT 127.0.0.1:8080/api/teams/team_1
Content-Type: application/json

{
  "name": "WhatTheFuck2",
  "players": ["player_2", "player_0", "player_22", "player_32"]
}

### Error : Delete with unknown team
DELETE 127.0.0.1:8080/api/teams/unknown