###
GET 127.0.0.1:8080/api/players

###
POST 127.0.0.1:8080/api/players
Content-Type: application/json

{
  "firstname": "John",
  "lastname": "Doe"
}

###
PUT 127.0.0.1:8080/api/players/player_70826a83-4525-433d-8d8a-c6bc050a3f82
Content-Type: application/json

{
  "firstname": "John2",
  "lastname": "Doe2"
}

###
DELETE 127.0.0.1:8080/api/players/player_2871d657-5209-432b-9c37-e8cb8d1004bc

###
GET 127.0.0.1:8080/api/teams

###
GET 127.0.0.1:8080/api/teams/team_1

###
GET 127.0.0.1:8080/api/teams/team_1/stats

###
GET 127.0.0.1:8080/api/games

###
GET 127.0.0.1:8080/api/contestant-stats