# Configure H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configure DataSource
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configure Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.servlet.context-path=/api
server.error.path=/error
spreadsheet.id = 1CR_lb2J2UcYMNqxCiTJCuGDhlLrl8bN9gytmPshbXJU

#logging.level.root=DEBUG
#logging.level.org.springframework=DEBUG
#logging.level.com.gberard.tournament=DEBUG
#logging.level.org.springframework.data=DEBUG