# Configure DataSource
spring.datasource.url=${APP_DATASOURCE_URL:jdbc:postgresql://localhost:5432/tournament_manager}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${APP_DATASOURCE_USERNAME:tournament}
spring.datasource.password=${APP_DATASOURCE_PASSWORD:}
