# Configure H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configure DataSource
spring.datasource.url=${APP_DATASOURCE_URL:jdbc:h2:mem:testdb}
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=${APP_DATASOURCE_USERNAME:sa}
spring.datasource.password=${APP_DATASOURCE_PASSWORD:}
