name: Front - ReactJS
on:
  push:
    paths:
      - 'front/**'
permissions:
  contents: write
jobs:
  build:
    name: Build and Test 🔧
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Install and Build
          working-directory: front/
          run: |
            npm install
            npm test
            npm run build
        - name: Caching dist
          uses: actions/cache@v2
          id: cache-dist
          with:
            path: front/dist
            key: ${{ github.sha }}

  deploy:
    name: Package and Deploy 🚀
    if: github.ref_name == 'main'
    concurrency: ci-front-${{ github.ref }}
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Retrieving dist
        uses: actions/cache@v2
        id: cache-dist
        with:
          path: front/dist
          key: ${{ github.sha }}
      - name: Install and Build
        working-directory: front/
        run: |
          npm install
          npm run build
      - id: auth
        uses: google-github-actions/auth@v0.7.3
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Deploy to Cloud Storage
        uses: google-github-actions/upload-cloud-storage@v0
        id: 'upload-folder'
        with:
          path: 'front/dist'
          destination: 'static-scuf-tournois-prod'
          gzip: false
          parent: false
          headers: |-
            cache-control:no-cache,max-age=0


